/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#001b31",
        "primary-container": "#12304a",
        "on-primary": "#ffffff",
        "on-primary-container": "#7d98b7",
        "primary-fixed": "#cfe5ff",
        "primary-fixed-dim": "#adc9ea",
        "on-primary-fixed": "#001d34",
        "on-primary-fixed-variant": "#2d4964",
        "inverse-primary": "#adc9ea",

        "secondary": "#166b55",
        "secondary-container": "#a4f2d6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1f715a",
        "secondary-fixed": "#a4f2d6",
        "secondary-fixed-dim": "#89d5ba",
        "on-secondary-fixed": "#002117",
        "on-secondary-fixed-variant": "#00513f",

        "tertiary": "#261600",
        "tertiary-container": "#422900",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c68a25",
        "tertiary-fixed": "#ffddb2",
        "tertiary-fixed-dim": "#feba52",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#624000",

        "background": "#f4faff",
        "on-background": "#111d23",
        "surface": "#f4faff",
        "surface-dim": "#cfdce4",
        "surface-bright": "#f4faff",
        "surface-variant": "#d7e4ec",
        "surface-tint": "#46617d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e9f6fd",
        "surface-container": "#e3f0f8",
        "surface-container-high": "#ddeaf2",
        "surface-container-highest": "#d7e4ec",
        "on-surface": "#111d23",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#263238",
        "inverse-on-surface": "#e6f3fb",

        "outline": "#73777e",
        "outline-variant": "#c3c7ce",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "code-statutory": ["Inter", "monospace"],
      },
      fontSize: {
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "table-data": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "code-statutory": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
