/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Premium Institutional Government Palette
        "gov-navy": "#082B52",
        "gov-blue": "#0B3A6E",
        "gov-saffron": "#F39A24",
        "gov-green": "#16845B",
        "gov-bg": "#F4F6F8",
        "gov-dark": "#17212B",
        "gov-border": "#D5DCE4",

        "primary": "#082B52",
        "primary-container": "#0B3A6E",
        "on-primary": "#ffffff",
        "on-primary-container": "#cfe5ff",
        "primary-fixed": "#e3eff8",
        "primary-fixed-dim": "#b5d4ec",
        "on-primary-fixed": "#082B52",
        "on-primary-fixed-variant": "#0B3A6E",
        "inverse-primary": "#a6c9ea",

        "secondary": "#16845B",
        "secondary-container": "#e1f5ee",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0c5036",
        "secondary-fixed": "#d0f0e4",
        "secondary-fixed-dim": "#9ee0ca",
        "on-secondary-fixed": "#062b1d",
        "on-secondary-fixed-variant": "#16845B",

        "tertiary": "#F39A24",
        "tertiary-container": "#fef5e7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7a4807",
        "tertiary-fixed": "#fdebd0",
        "tertiary-fixed-dim": "#f8c471",
        "on-tertiary-fixed": "#3e2202",
        "on-tertiary-fixed-variant": "#87500a",

        "background": "#F4F6F8",
        "on-background": "#17212B",
        "surface": "#F4F6F8",
        "surface-dim": "#e8edf2",
        "surface-bright": "#FFFFFF",
        "surface-variant": "#dfe6ed",
        "surface-tint": "#0B3A6E",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f9fa",
        "surface-container": "#f0f4f7",
        "surface-container-high": "#e5ecf1",
        "surface-container-highest": "#dbe4eb",
        "on-surface": "#17212B",
        "on-surface-variant": "#495057",
        "inverse-surface": "#17212B",
        "inverse-on-surface": "#f4f6f8",

        "outline": "#8a96a3",
        "outline-variant": "#d5dce4",

        "error": "#b91c1c",
        "error-container": "#fee2e2",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d",
      },
      borderRadius: {
        DEFAULT: "0.5rem", // 8px
        sm: "0.375rem",    // 6px
        md: "0.5rem",      // 8px
        lg: "0.625rem",    // 10px
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "code-statutory": ["Inter", "monospace"],
      },
      fontSize: {
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "table-data": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "code-statutory": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
