import { OFFICIAL_KNOWLEDGE_BASE } from "./regulatoryKnowledgeBase";

export const initialBusinessProfile = {
  id: "biz-001",
  legalName: "ABC Foods Pvt. Ltd.",
  brandName: "ABC Foods",
  referenceId: "MH-NSK-2024-F8821",
  sector: "Food Processing",
  sectorCategory: "Grain Mill Products & Commercial Packaging",
  nicCode: "10612 & 10792",
  entityType: "Private Limited Company",
  classification: "Small Enterprise",
  stage: "Starting a new business",
  stageLabel: "Greenfield Setup (Pre-operational)",
  incorporatedDate: "2024-01-12",
  udyamNumber: "UDYAM-MH-26-0038912",
  cin: "U15400MH2024PTC419820",
  pan: "AABCA9128K",
  gstin: "27AABCA9128K1Z3",

  // Jurisdiction & Location
  state: "Maharashtra",
  district: "Nashik",
  taluka: "Nashik",
  industrialArea: "MIDC Ambad Industrial Estate",
  plotNumber: "Plot No. W-48, Phase II",
  pinCode: "422010",
  localBody: "Nashik Municipal Corporation (NMC)",

  // Operations
  operations: ["Manufacturing", "Packaging", "Storage"],
  coldStoragePlanned: true,
  workforceCount: 28,
  connectedLoadHP: 45,
  connectedLoadKVA: 55,
  dailyProductionCapacityMT: 0.85,

  // Financial Outlay
  plantMachineryInvestment: 45000000, // 4.5 Cr
  annualTurnoverEstimated: 182000000, // 18.2 Cr
  landBuildingInvestment: 32000000, // 3.2 Cr
  totalProjectCost: 77000000, // 7.7 Cr

  // Authorized Signatory
  contactPerson: "Rajesh Sharma",
  designation: "Managing Director & Signatory",
  email: "rajesh.sharma@abcfoods.in",
  phone: "+91 98220 45678",
  status: "Active MSME",
  lastUpdated: "2024-09-18",
};

export const initialRequirements = OFFICIAL_KNOWLEDGE_BASE;

export const initialDocuments = [
  {
    id: "doc-1",
    name: "Certificate of Incorporation.pdf",
    category: "Statutory Identity",
    docType: "Corporate Registration",
    size: "1.8 MB",
    uploadedAt: "2024-02-14",
    status: "verified",
    verifiedBy: "MCA Portal Cross-check",
    requirementRef: ["fssai-license", "mpcb-cte", "gumasta-license"],
    notes: "Verified against CIN: U15400MH2024PTC419820",
  },
  {
    id: "doc-2",
    name: "MoA_and_AoA_Executed.pdf",
    category: "Statutory Identity",
    docType: "Constitutional Charter",
    size: "3.4 MB",
    uploadedAt: "2024-02-14",
    status: "verified",
    verifiedBy: "ROC Pune Certified Copy",
    requirementRef: ["fssai-license", "mpcb-cte"],
    notes: "Objects clause explicitly authorizes Food Processing and Packaging activities.",
  },
  {
    id: "doc-3",
    name: "Directors_PAN_Aadhaar_KYC_Bundle.pdf",
    category: "Statutory Identity",
    docType: "Identity Proof",
    size: "2.1 MB",
    uploadedAt: "2024-02-18",
    status: "verified",
    verifiedBy: "DigiLocker API Check",
    requirementRef: ["fssai-license", "gumasta-license"],
    notes: "KYC credentials for Rajesh Sharma and Priya Sharma verified.",
  },
  {
    id: "doc-4",
    name: "MIDC_Ambad_Allotment_Lease_Deed.pdf",
    category: "Premises & Land",
    docType: "Land Tenure",
    size: "6.2 MB",
    uploadedAt: "2024-03-01",
    status: "verified",
    verifiedBy: "MIDC Nashik Sub-Registry",
    requirementRef: ["mpcb-cte", "gumasta-license"],
    notes: "95-year industrial lease deed for Plot No. W-48, Ambad Phase II.",
  },
  {
    id: "doc-5",
    name: "NMC_Property_Tax_Challan_2024.pdf",
    category: "Premises & Land",
    docType: "Municipal Clearance",
    size: "820 KB",
    uploadedAt: "2024-03-10",
    status: "verified",
    verifiedBy: "NMC Revenue Portal",
    requirementRef: ["gumasta-license"],
    notes: "Up-to-date assessment paid for municipal ward 14.",
  },
  {
    id: "doc-6",
    name: "Nashik_Factory_Premises_Blueprint_v1.pdf",
    category: "Technical & Engineering",
    docType: "Premises Layout Plan",
    size: "4.5 MB",
    uploadedAt: "2024-03-15",
    status: "verified",
    verifiedBy: "Licensed Industrial Architect",
    requirementRef: ["fssai-license", "mpcb-cte"],
    notes: "Floor plan illustrates raw material dock, clean room, packaging line, and effluent sump.",
  },
  {
    id: "doc-7",
    name: "Installed_Machinery_Horsepower_Schedule.pdf",
    category: "Technical & Engineering",
    docType: "Machinery Inventory",
    size: "1.1 MB",
    uploadedAt: "2024-03-18",
    status: "action_required",
    verifiedBy: "Pending Chartered Engineer Endorsement",
    requirementRef: ["fssai-license", "mpcb-cte"],
    notes: "Missing OEM test certificates for 25 HP micro-pulverizer and 15 HP packaging sealer.",
  },
  {
    id: "doc-8",
    name: "Water_Potability_Lab_Report_NABL.pdf",
    category: "Environmental & Lab",
    docType: "Laboratory Test Report",
    size: "950 KB",
    uploadedAt: "2024-03-20",
    status: "action_required",
    verifiedBy: "Awaiting NABL Resample Verification",
    requirementRef: ["fssai-license"],
    notes: "Current report is 7 months old; FSSAI requires NABL report within 180 days.",
  },
  {
    id: "doc-9",
    name: "Signboard_Marathi_Devanagari_Frontage.jpg",
    category: "Premises & Land",
    docType: "Photographic Evidence",
    size: "2.4 MB",
    uploadedAt: "2024-03-21",
    status: "action_required",
    verifiedBy: "Pending Shop Act Review",
    requirementRef: ["gumasta-license"],
    notes: "Uploaded photo is obstructed by temporary gate scaffolding. Needs clear high-res photo.",
  },
];

export const initialComplianceTasks = [
  {
    id: "comp-1",
    title: "FSSAI Annual Return Filing (Form D-1)",
    frequency: "Annual",
    dueDate: "2024-05-31",
    authority: "FSSAI / FoSCoS",
    status: "Upcoming",
    urgency: "Due in 42 Days",
    category: "Food Safety",
    description: "Statutory declaration of food products manufactured, handled, imported, or distributed during the financial year.",
    penaltyRisk: "₹100 per day penalty for delay under Section 2.1.13 of FSS Licensing Regulations.",
    filingPortal: "https://foscos.fssai.gov.in",
  },
  {
    id: "comp-2",
    title: "MPCB Environmental Statement (Form V)",
    frequency: "Annual",
    dueDate: "2024-09-30",
    authority: "Maharashtra Pollution Control Board",
    status: "Scheduled",
    urgency: "Upcoming in Q3",
    category: "Environment",
    description: "Annual submission of raw materials consumed, water consumption, and pollution loads generated under EPA 1986.",
    penaltyRisk: "Potential show-cause notice and forfeit of bank guarantee under Orange category.",
    filingPortal: "https://mpcb.gov.in",
  },
  {
    id: "comp-3",
    title: "Factories Act Annual Return (Form 27)",
    frequency: "Annual",
    dueDate: "2025-02-01",
    authority: "DISH Maharashtra",
    status: "Scheduled",
    urgency: "Q4 Obligation",
    category: "Labor & Safety",
    description: "Consolidated report of average daily employment, hours worked, industrial accidents, and welfare facilities.",
    penaltyRisk: "Fine up to ₹1,00,000 under Section 92 of the Factories Act.",
    filingPortal: "https://dish.maharashtra.gov.in",
  },
  {
    id: "comp-4",
    title: "Maharashtra Professional Tax (P-Tax) Return & Challan",
    frequency: "Monthly",
    dueDate: "2024-04-30",
    authority: "Maharashtra State Tax Department",
    status: "Action Required",
    urgency: "Due in 11 Days",
    category: "State Taxation",
    description: "Monthly deposit of deducted professional tax for 28 employees under Maharashtra State Tax on Professions Act.",
    penaltyRisk: "1.25% monthly interest plus 10% penalty on unpaid amount.",
    filingPortal: "https://mahagst.gov.in",
  },
  {
    id: "comp-5",
    title: "GST Monthly Return Filing (GSTR-3B)",
    frequency: "Monthly",
    dueDate: "2024-04-20",
    authority: "GSTN / Maharashtra GST",
    status: "Completed",
    urgency: "Filed On-Time",
    category: "Indirect Tax",
    description: "Summary return of outward supplies and input tax credit claimed for the preceding month.",
    penaltyRisk: "Late fee ₹50/day plus 18% per annum interest on net tax liability.",
    filingPortal: "https://gst.gov.in",
  },
  {
    id: "comp-6",
    title: "Quarterly Water Quality & ETP Log Assessment",
    frequency: "Quarterly",
    dueDate: "2024-06-30",
    authority: "Internal / MPCB Compliance",
    status: "Upcoming",
    urgency: "Scheduled",
    category: "Internal Audit",
    description: "Quarterly maintenance and pH/TDS logs of effluent neutralization tank.",
    penaltyRisk: "Statutory condition imposed under CTE Clause 7.",
    filingPortal: "Internal Records Log",
  },
];

export const initialGovernmentSupport = [
  {
    id: "scheme-psi-2019",
    title: "Maharashtra Package Scheme of Incentives (PSI) 2019",
    authority: "Directorate of Industries, Government of Maharashtra",
    tier: "State Industrial Policy (Zone C - Nashik)",
    matchScore: 96,
    badge: "HIGH SUBSIDY MATCH",
    badgeColor: "emerald",
    eligibilityStatus: "Eligible for Application",
    maxBenefitEstimate: "₹2,25,00,000 (Up to 50% of Eligible Capital Outlay)",
    summary:
      "Designed to promote industrial dispersal in Maharashtra. Zone C (Nashik) provides premier capital incentives, GST reimbursement, electricity duty waivers, and interest subsidies for MSME food processing units.",
    keyBenefits: [
      "50% Capital Investment Subsidy on eligible plant & machinery investment.",
      "100% Electricity Duty Exemption for 7 continuous operational years.",
      "5% Interest Subvention on Term Loans for 5 years up to ₹10 Lakhs per annum.",
      "Gross SGST Reimbursement up to 70% of eligible fixed capital investment.",
    ],
    eligibilityChecklist: [
      { item: "Located in MIDC Ambad (Qualifies as Zone C)", met: true },
      { item: "Food Processing classified as Thrust Sector", met: true },
      { item: "Valid Udyam Registration (Small Enterprise)", met: true },
      { item: "Commencement of commercial production within 36 months", met: true },
    ],
    officialPortalUrl: "https://di.maharashtra.gov.in",
    portalName: "Maitri Single Window Industrial Portal",
    applicationTimeline: "Apply within 6 months of commercial production",
  },
  {
    id: "scheme-pmfme",
    title: "PM Formalisation of Micro Food Processing Enterprises (PMFME) Scheme",
    authority: "Ministry of Food Processing Industries (MoFPI) / Maharashtra Agril Dept",
    tier: "Centrally Sponsored Scheme (Aatmanirbhar Bharat)",
    matchScore: 92,
    badge: "CREDIT-LINKED GRANT",
    badgeColor: "emerald",
    eligibilityStatus: "Eligible for Application",
    maxBenefitEstimate: "₹10,00,000 (35% Credit-Linked Capital Subsidy)",
    summary:
      "Provides financial, technical and business support for the up-gradation of micro & small food processing enterprises. In Maharashtra, it aligns with the One District One Product (ODOP) initiative for grapes, onions, and cereal value addition in Nashik.",
    keyBenefits: [
      "35% Credit-linked capital subsidy with a ceiling of ₹10 Lakhs per enterprise.",
      "Marketing and branding support for cluster level exports.",
      "Technical training assistance via NIFTEM and CFTRI.",
    ],
    eligibilityChecklist: [
      { item: "Ownership status: Pvt Ltd MSME with individual equity > 51%", met: true },
      { item: "Product line aligned with Nashik agro-processing", met: true },
      { item: "Formal bank term loan sanction letter attached", met: false },
    ],
    officialPortalUrl: "https://pmfme.mofpi.gov.in",
    portalName: "MoFPI National PMFME Portal",
    applicationTimeline: "Open for continuous enrollment",
  },
  {
    id: "scheme-sampada",
    title: "Pradhan Mantri Kisan SAMPADA Yojana (CEFPPC)",
    authority: "Ministry of Food Processing Industries (MoFPI)",
    tier: "Central Sector Scheme",
    matchScore: 84,
    badge: "INFRASTRUCTURE GRANT",
    badgeColor: "blue",
    eligibilityStatus: "Requires Detailed Project Report (DPR)",
    maxBenefitEstimate: "₹5,00,00,000 (35% Grant-in-aid of eligible project cost)",
    summary:
      "Creation and Expansion of Food Processing & Preservation Capacities (CEFPPC). Supports setting up processing units to modernize farm-to-fork supply chains and reduce post-harvest waste.",
    keyBenefits: [
      "Capital grant-in-aid of 35% of eligible plant, machinery and technical civil works.",
      "Cold-chain and modern sorting-grading line funding.",
    ],
    eligibilityChecklist: [
      { item: "Minimum project cost ₹3 Crores (ABC Foods: ₹7.7 Cr)", met: true },
      { item: "DPR prepared by MoFPI empaneled consultant", met: false },
      { item: "Term loan appraised by Scheduled Commercial Bank", met: false },
    ],
    officialPortalUrl: "https://www.mofpi.gov.in",
    portalName: "MoFPI SAMPADA Portal",
    applicationTimeline: "Subject to periodic Expression of Interest (EoI) windows",
  },
  {
    id: "scheme-cgtmse",
    title: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
    authority: "Ministry of MSME & SIDBI",
    tier: "National Credit Mechanism",
    matchScore: 88,
    badge: "COLLATERAL-FREE CREDIT",
    badgeColor: "amber",
    eligibilityStatus: "Pre-approved Banking Route",
    maxBenefitEstimate: "Collateral-free debt up to ₹2,00,00,000 (₹2 Crores)",
    summary:
      "Provides credit guarantee coverage up to 85% for micro and small enterprises seeking working capital or term loans without third-party collateral or land mortgage.",
    keyBenefits: [
      "Credit guarantee cover up to 85% for loans up to ₹2 Crores.",
      "Reduced processing charges and expedited loan sanction via SIDBI partner banks.",
    ],
    eligibilityChecklist: [
      { item: "Valid Udyam Registration certificate", met: true },
      { item: "Clean CIBIL commercial credit track record", met: true },
    ],
    officialPortalUrl: "https://www.cgtmse.in",
    portalName: "CGTMSE Official Portal",
    applicationTimeline: "Avail through any public or private scheduled bank",
  },
];
